### PR TITLE
Linux Live OS support and automated testing

### PR DESCRIPTION
**Pull request by sdolenc**
This pull request replaces https://github.com/Algodev-github/S/pull/3

Overview:
- Adding support for linux live operating systems which host their file system on a temporary ram-disk. I tested on Xubuntu, Puppy Linux, Slax, MX linux
- Introduces automated testing with bats-core. The tests primarily cover the areas of code I'm changing, but test cases can be easily added to cover more in the future.
- You mentioned "this suite is often used on systems running older software" so the tests are run on a wide range of BASH versions for free on circleci (example screenshot below).

image

### CODE REVIEW

**Comment by sdolenc** [comment]
Is this a change you would consider merging? If so, I'd be happy to resolve the merge conflict. I also don't mind moving the continuous integration tests to a different CI provider (my other favorite is GitHub Actions).

Let me know if you have other design feedback too :) thanks!

**Comment by Algodev-github** [comment]
> Is this a change you would consider merging? If so, I'd be happy to resolve the merge conflict. I also don't mind moving the continuous integration tests to a different CI provider (my other favorite is GitHub Actions).
> 
> Let me know if you have other design feedback too :) thanks!

I'm sorry I pushed other stuff before merging this PR (crazy time here in Italy, easier to get distracted, be patient). Yes, resolve conflicts please. Your PR will be the next change I'll work on.

**Comment by sdolenc** [comment]
sounds good :) no rush. I'll do some more testing and resolve conflicts this week.

**Comment by sdolenc** [comment]
conflicts resolved :+1:

**Comment by Algodev-github** [comment]
I had a look at your pull request on GitHub, but it still says "This branch cannot be rebased due to conflicts". What am I missing? (I'm sorry, but I started acting as a puller on Github basically since you request ...)

**Comment by sdolenc** [comment]
That's odd. The pr says "this branch has no conflicts with the base branch"
image

One possibility: If you're trying to rebase or merge locally then you may need to try fetching the latest of my fork. For example, `git remote -v` may show you something like
 - origin github.com/Algodev-github/S
 - fork2 github.com/sdolenc/S

You would want to run something like `git fetch fork2` (probably isn't fork2, but as an example)

Not sure what else could be the cause or possible resolutions offhand. Feel free to provide more information about any issues you're seeing and I'll try my best to help.

**Comment by Algodev-github** [comment]
Found the problem: I had the option "Rebase and merge" selected; probably because it's the option I chose the last time I merged a pull request. This option is evidently unfeasible with this pull request, because it now contains a merge commit. In this respect, I'd prefer to keep the story linear. Would it be ok for you to make a PR without a merge commit? Or are there good reasons why it would be better to go for a "Create a merge commit"? Sorry for making you waste more time.

**Comment by sdolenc** [comment]
I don't mind submitting a new PR with simpler commits. I'll aim to put that together when I have the chance (probably within a week)

I merged master into my branch to resolve the conflict. I didn't know a merge commit prevents rebasing, but that makes sense.

Let me know if you prefer GitHub Actions over circle ci. I'd be happy to switch it with the new pr if so

**Comment by Algodev-github** [comment]
No no, better no switch, let's avoid introducing more variable again my weak knowledge :)

Looking forward to your new pull request,
Paolo

**Comment by sdolenc** [comment]
https://github.com/Algodev-github/S/pull/6 replaces this pr

**Pull request closed without merging**
